/// Display formatting functions for roadmaps, phases, and projects.
///
/// Pure functions — no I/O. These produce human-readable output strings.
use crate::ast;
use crate::document::Document;
use crate::model::{Phase, PhaseStatus, Roadmap, Task};
use crate::search::SearchResult;

/// Aggregated index data for a single project.
pub struct ProjectIndex {
    /// Project name.
    pub name: String,
    /// Roadmap index entries, pre-sorted by slug.
    pub roadmaps: Vec<RoadmapIndexEntry>,
    /// Tasks as `(slug, Document<Task>)`, pre-sorted by priority desc then slug asc.
    pub tasks: Vec<(String, Document<Task>)>,
}

/// Summary data for a roadmap in the index.
pub struct RoadmapIndexEntry {
    /// Roadmap slug.
    pub slug: String,
    /// Project this roadmap belongs to.
    pub project: String,
    /// Total number of phases.
    pub phase_count: usize,
    /// Number of completed phases.
    pub done_count: usize,
    /// Optional list of dependency roadmap slugs.
    pub dependencies: Option<Vec<String>>,
}

/// Formats the plan index as a Markdown string.
///
/// Produces the complete `INDEX.md` content from pre-aggregated project data.
#[must_use]
pub fn format_index(projects: &[ProjectIndex]) -> String {
    let mut d = ast::Document::new();
    d.heading(1, "Plan Index");
    d.push(ast::Block::BlankLine);
    d.push(ast::Block::HtmlComment(
        "This file is auto-generated by rdm. Do not edit by hand.".to_owned(),
    ));

    for project in projects {
        d.push(ast::Block::BlankLine);
        d.heading(2, &format!("Project: {}", project.name));
        d.push(ast::Block::BlankLine);

        // Roadmaps table
        if project.roadmaps.is_empty() {
            d.paragraph("No roadmaps.");
        } else {
            let headers = vec!["Roadmap", "Phases", "Progress", "Dependencies"]
                .into_iter()
                .map(|h| vec![ast::Inline::text(h)])
                .collect();
            let rows = project
                .roadmaps
                .iter()
                .map(|rm| {
                    let progress = if rm.phase_count == 0 {
                        "no phases".to_string()
                    } else if rm.done_count == 0 {
                        "not started".to_string()
                    } else if rm.done_count == rm.phase_count {
                        "complete".to_string()
                    } else {
                        format!("{}/{} done", rm.done_count, rm.phase_count)
                    };
                    let deps = rm
                        .dependencies
                        .as_ref()
                        .map(|dep| dep.join(", "))
                        .unwrap_or_else(|| "\u{2014}".to_string());
                    let link_url =
                        format!("projects/{}/roadmaps/{}/roadmap.md", rm.project, rm.slug);
                    vec![
                        vec![ast::Inline::link(&rm.slug, &link_url)],
                        vec![ast::Inline::Text(rm.phase_count.to_string())],
                        vec![ast::Inline::Text(progress)],
                        vec![ast::Inline::Text(deps)],
                    ]
                })
                .collect();
            d.push(ast::Block::Table { headers, rows });

            // Dependency graph (only if any roadmap has deps)
            let has_deps = project
                .roadmaps
                .iter()
                .any(|rm| rm.dependencies.as_ref().is_some_and(|dep| !dep.is_empty()));
            if has_deps {
                d.push(ast::Block::BlankLine);
                d.heading(3, "Dependency Graph");
                d.push(ast::Block::BlankLine);
                let items = project
                    .roadmaps
                    .iter()
                    .filter(|rm| rm.dependencies.as_ref().is_some_and(|dep| !dep.is_empty()))
                    .map(|rm| {
                        let deps = rm.dependencies.as_ref().unwrap();
                        vec![
                            ast::Inline::bold(&rm.slug),
                            ast::Inline::Text(format!(" \u{2192} {}", deps.join(", "))),
                        ]
                    })
                    .collect();
                d.push(ast::Block::UnorderedList { items });
            }
        }

        // Tasks table
        d.push(ast::Block::BlankLine);
        if project.tasks.is_empty() {
            d.paragraph("No tasks.");
        } else {
            let headers = vec!["Task", "Priority", "Status"]
                .into_iter()
                .map(|h| vec![ast::Inline::text(h)])
                .collect();
            let rows = project
                .tasks
                .iter()
                .map(|(slug, doc)| {
                    let fm = &doc.frontmatter;
                    vec![
                        vec![ast::Inline::Text(slug.clone())],
                        vec![ast::Inline::Text(fm.priority.to_string())],
                        vec![ast::Inline::Text(fm.status.to_string())],
                    ]
                })
                .collect();
            d.push(ast::Block::Table { headers, rows });
        }
    }

    d.to_string()
}

/// A roadmap document paired with its phases (stem + phase document).
pub type RoadmapWithPhases = (Document<Roadmap>, Vec<(String, Document<Phase>)>);

/// Formats a roadmap summary with a status table of its phases and optional body.
///
/// Displays the roadmap title, project/slug metadata, phase progress table,
/// and any body content from the document. If the document body is non-empty,
/// it is appended after the phase table (or "No phases yet." message).
pub fn format_roadmap_summary(
    doc: &Document<Roadmap>,
    phases: &[(String, Document<Phase>)],
) -> String {
    let roadmap = &doc.frontmatter;
    let mut d = ast::Document::new();
    d.heading(1, &roadmap.title);
    d.push(ast::Block::BlankLine);
    d.paragraph(&format!(
        "Project: {}  Slug: {}",
        roadmap.project, roadmap.roadmap
    ));

    if phases.is_empty() {
        d.push(ast::Block::BlankLine);
        d.paragraph("No phases yet.");
    } else {
        let done_count = phases
            .iter()
            .filter(|(_, pd)| pd.frontmatter.status == PhaseStatus::Done)
            .count();
        d.paragraph(&format!(
            "Progress: {}/{} phases done",
            done_count,
            phases.len()
        ));
        d.push(ast::Block::BlankLine);

        let headers = vec!["#", "Phase", "Status"]
            .into_iter()
            .map(|h| vec![ast::Inline::text(h)])
            .collect();
        let rows = phases
            .iter()
            .map(|(_, pd)| {
                let fm = &pd.frontmatter;
                vec![
                    vec![ast::Inline::Text(fm.phase.to_string())],
                    vec![ast::Inline::Text(fm.title.clone())],
                    vec![ast::Inline::Text(fm.status.to_string())],
                ]
            })
            .collect();
        d.push(ast::Block::Table { headers, rows });
    }

    if !doc.body.is_empty() {
        d.push(ast::Block::BlankLine);
        d.raw(&doc.body);
    }
    d.to_string()
}

/// Formats a single phase detail view.
pub fn format_phase_detail(stem: &str, doc: &Document<Phase>) -> String {
    let fm = &doc.frontmatter;
    let mut d = ast::Document::new();
    d.heading(1, &format!("Phase {}: {}", fm.phase, fm.title));
    d.push(ast::Block::BlankLine);
    d.paragraph(&format!("Stem: {stem}"));
    d.paragraph(&format!("Status: {}", fm.status));
    if let Some(date) = fm.completed {
        d.paragraph(&format!("Completed: {date}"));
    }
    if !doc.body.is_empty() {
        d.push(ast::Block::BlankLine);
        d.raw(&doc.body);
    }
    d.to_string()
}

/// Formats a list of phases as a table with number, title, status, and stem.
pub fn format_phase_list(phases: &[(String, Document<Phase>)]) -> String {
    let mut doc = ast::Document::new();
    if phases.is_empty() {
        doc.paragraph("No phases yet.");
    } else {
        let headers = vec!["#", "Phase", "Status", "Stem"]
            .into_iter()
            .map(|h| vec![ast::Inline::text(h)])
            .collect();
        let rows = phases
            .iter()
            .map(|(stem, d)| {
                let fm = &d.frontmatter;
                vec![
                    vec![ast::Inline::Text(fm.phase.to_string())],
                    vec![ast::Inline::Text(fm.title.clone())],
                    vec![ast::Inline::Text(fm.status.to_string())],
                    vec![ast::Inline::Text(stem.clone())],
                ]
            })
            .collect();
        doc.push(ast::Block::Table { headers, rows });
    }
    doc.to_string()
}

/// Formats a list of roadmaps with progress summaries.
pub fn format_roadmap_list(entries: &[RoadmapWithPhases]) -> String {
    let mut d = ast::Document::new();
    if entries.is_empty() {
        d.paragraph("No roadmaps found.");
    } else {
        for (roadmap_doc, phases) in entries {
            let rm = &roadmap_doc.frontmatter;
            let done = phases
                .iter()
                .filter(|(_, pd)| pd.frontmatter.status == PhaseStatus::Done)
                .count();
            let total = phases.len();
            if total > 0 {
                d.paragraph(&format!(
                    "{} — {} ({}/{} done)",
                    rm.roadmap, rm.title, done, total
                ));
            } else {
                d.paragraph(&format!("{} — {} (no phases)", rm.roadmap, rm.title));
            }
        }
    }
    d.to_string()
}

/// Formats a single task detail view.
pub fn format_task_detail(slug: &str, doc: &Document<Task>) -> String {
    let fm = &doc.frontmatter;
    let mut d = ast::Document::new();
    d.heading(1, &fm.title);
    d.push(ast::Block::BlankLine);
    d.paragraph(&format!("Slug: {slug}"));
    d.paragraph(&format!("Status: {}", fm.status));
    d.paragraph(&format!("Priority: {}", fm.priority));
    d.paragraph(&format!("Created: {}", fm.created));
    if let Some(tags) = &fm.tags {
        d.paragraph(&format!("Tags: {}", tags.join(", ")));
    }
    if !doc.body.is_empty() {
        d.push(ast::Block::BlankLine);
        d.raw(&doc.body);
    }
    d.to_string()
}

/// Formats a list of tasks as a table with slug, title, status, and priority columns.
pub fn format_task_list(tasks: &[(String, Document<Task>)]) -> String {
    let mut doc = ast::Document::new();
    if tasks.is_empty() {
        doc.paragraph("No tasks found.");
    } else {
        let headers = vec!["Slug", "Title", "Status", "Priority"]
            .into_iter()
            .map(|h| vec![ast::Inline::text(h)])
            .collect();
        let rows = tasks
            .iter()
            .map(|(slug, d)| {
                let fm = &d.frontmatter;
                vec![
                    vec![ast::Inline::Text(slug.clone())],
                    vec![ast::Inline::Text(fm.title.clone())],
                    vec![ast::Inline::Text(fm.status.to_string())],
                    vec![ast::Inline::Text(fm.priority.to_string())],
                ]
            })
            .collect();
        doc.push(ast::Block::Table { headers, rows });
    }
    doc.to_string()
}

/// Formats a dependency graph as a human-readable list.
///
/// Each entry shows a roadmap and what it depends on.
/// If the graph is empty, returns a message indicating no dependencies.
#[must_use]
pub fn format_dependency_graph(graph: &[(String, Vec<String>)]) -> String {
    let mut d = ast::Document::new();
    if graph.is_empty() {
        d.paragraph("No dependencies found.");
    } else {
        for (slug, deps) in graph {
            d.paragraph(&format!("{slug} → {}", deps.join(", ")));
        }
    }
    d.to_string()
}

/// Formats search results as a ranked text table.
#[must_use]
pub fn format_search_results(results: &[SearchResult]) -> String {
    if results.is_empty() {
        return String::new();
    }

    let headers = vec!["#", "Type", "Title", "Identifier", "Snippet"]
        .into_iter()
        .map(|h| vec![ast::Inline::text(h)])
        .collect();
    let rows = results
        .iter()
        .enumerate()
        .map(|(i, r)| {
            let snippet = truncate_snippet(&r.snippet, 40);
            vec![
                vec![ast::Inline::Text((i + 1).to_string())],
                vec![ast::Inline::Text(r.kind.to_string())],
                vec![ast::Inline::Text(r.title.clone())],
                vec![ast::Inline::Text(r.identifier.clone())],
                vec![ast::Inline::Text(snippet)],
            ]
        })
        .collect();

    let mut d = ast::Document::new();
    d.push(ast::Block::Table { headers, rows });
    d.to_string()
}

/// Truncates a snippet to `max_len` characters, appending "..." if needed.
fn truncate_snippet(s: &str, max_len: usize) -> String {
    let trimmed = s.trim();
    if trimmed.len() <= max_len {
        return trimmed.to_string();
    }
    let mut end = max_len;
    while end > 0 && !trimmed.is_char_boundary(end) {
        end -= 1;
    }
    format!("{}...", &trimmed[..end])
}

/// Formats a roadmap summary as Markdown with heading, bullet metadata, phase table, and body.
#[must_use]
pub fn format_roadmap_summary_md(
    doc: &Document<Roadmap>,
    phases: &[(String, Document<Phase>)],
) -> String {
    let roadmap = &doc.frontmatter;
    let mut out = String::new();
    out.push_str(&format!("# {}\n\n", roadmap.title));
    out.push_str(&format!("- **Project:** {}\n", roadmap.project));
    out.push_str(&format!("- **Slug:** {}\n", roadmap.roadmap));

    if phases.is_empty() {
        out.push_str("\nNo phases yet.\n");
    } else {
        let done_count = phases
            .iter()
            .filter(|(_, d)| d.frontmatter.status == PhaseStatus::Done)
            .count();
        out.push_str(&format!(
            "- **Progress:** {}/{} phases done\n",
            done_count,
            phases.len()
        ));

        out.push_str("\n| # | Phase | Status |\n");
        out.push_str("|---:|-------|--------|\n");
        for (_, d) in phases {
            let fm = &d.frontmatter;
            out.push_str(&format!(
                "| {} | {} | {} |\n",
                fm.phase, fm.title, fm.status
            ));
        }
    }

    if !doc.body.is_empty() {
        out.push_str(&format!("\n{}", doc.body));
    }
    out
}

/// Formats a list of roadmaps as a Markdown table.
#[must_use]
pub fn format_roadmap_list_md(entries: &[RoadmapWithPhases]) -> String {
    if entries.is_empty() {
        return "No roadmaps found.\n".to_string();
    }

    let mut out = String::new();
    out.push_str("## Roadmaps\n\n");
    out.push_str("| Slug | Title | Progress |\n");
    out.push_str("|------|-------|----------|\n");
    for (roadmap_doc, phases) in entries {
        let rm = &roadmap_doc.frontmatter;
        let done = phases
            .iter()
            .filter(|(_, doc)| doc.frontmatter.status == PhaseStatus::Done)
            .count();
        let total = phases.len();
        let progress = if total > 0 {
            format!("{done}/{total} done")
        } else {
            "no phases".to_string()
        };
        out.push_str(&format!(
            "| {} | {} | {} |\n",
            rm.roadmap, rm.title, progress
        ));
    }
    out
}

/// Formats a single phase detail as Markdown with heading, bullet metadata, and body.
#[must_use]
pub fn format_phase_detail_md(stem: &str, doc: &Document<Phase>) -> String {
    let fm = &doc.frontmatter;
    let mut out = String::new();
    out.push_str(&format!("# Phase {}: {}\n\n", fm.phase, fm.title));
    out.push_str(&format!("- **Stem:** {stem}\n"));
    out.push_str(&format!("- **Status:** {}\n", fm.status));
    if let Some(date) = fm.completed {
        out.push_str(&format!("- **Completed:** {date}\n"));
    }
    if !doc.body.is_empty() {
        out.push_str(&format!("\n{}", doc.body));
    }
    out
}

/// Formats a list of phases as a Markdown table.
#[must_use]
pub fn format_phase_list_md(phases: &[(String, Document<Phase>)]) -> String {
    if phases.is_empty() {
        return "No phases yet.\n".to_string();
    }

    let mut out = String::new();
    out.push_str("## Phases\n\n");
    out.push_str("| # | Phase | Status | Stem |\n");
    out.push_str("|---:|-------|--------|------|\n");
    for (stem, doc) in phases {
        let fm = &doc.frontmatter;
        out.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            fm.phase, fm.title, fm.status, stem
        ));
    }
    out
}

/// Formats a single task detail as Markdown with heading, bullet metadata, and body.
#[must_use]
pub fn format_task_detail_md(slug: &str, doc: &Document<Task>) -> String {
    let fm = &doc.frontmatter;
    let mut out = String::new();
    out.push_str(&format!("# {}\n\n", fm.title));
    out.push_str(&format!("- **Slug:** {slug}\n"));
    out.push_str(&format!("- **Status:** {}\n", fm.status));
    out.push_str(&format!("- **Priority:** {}\n", fm.priority));
    out.push_str(&format!("- **Created:** {}\n", fm.created));
    if let Some(tags) = &fm.tags {
        out.push_str(&format!("- **Tags:** {}\n", tags.join(", ")));
    }
    if !doc.body.is_empty() {
        out.push_str(&format!("\n{}", doc.body));
    }
    out
}

/// Formats a list of tasks as a Markdown table.
#[must_use]
pub fn format_task_list_md(tasks: &[(String, Document<Task>)]) -> String {
    if tasks.is_empty() {
        return "No tasks found.\n".to_string();
    }

    let mut out = String::new();
    out.push_str("## Tasks\n\n");
    out.push_str("| Slug | Title | Status | Priority |\n");
    out.push_str("|------|-------|--------|----------|\n");
    for (slug, doc) in tasks {
        let fm = &doc.frontmatter;
        out.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            slug, fm.title, fm.status, fm.priority
        ));
    }
    out
}

/// Formats search results as a Markdown table.
#[must_use]
pub fn format_search_results_md(results: &[SearchResult]) -> String {
    if results.is_empty() {
        return "No results found.\n".to_string();
    }

    let mut out = String::new();
    out.push_str("## Search Results\n\n");
    out.push_str("| # | Type | Title | Identifier | Snippet |\n");
    out.push_str("|---:|------|-------|------------|---------|\n");
    for (i, r) in results.iter().enumerate() {
        let snippet = truncate_snippet(&r.snippet, 40);
        out.push_str(&format!(
            "| {} | {} | {} | {} | {} |\n",
            i + 1,
            r.kind,
            r.title,
            r.identifier,
            snippet,
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{PhaseStatus, Priority, TaskStatus};
    use chrono::NaiveDate;

    fn make_phase_doc(num: u32, title: &str, status: PhaseStatus) -> Document<Phase> {
        Document {
            frontmatter: Phase {
                phase: num,
                title: title.to_string(),
                status,
                completed: if status == PhaseStatus::Done {
                    Some(NaiveDate::from_ymd_opt(2026, 3, 14).unwrap())
                } else {
                    None
                },
            },
            body: String::new(),
        }
    }

    fn make_roadmap(project: &str, slug: &str, title: &str) -> Roadmap {
        Roadmap {
            project: project.to_string(),
            roadmap: slug.to_string(),
            title: title.to_string(),
            phases: Vec::new(),
            dependencies: None,
        }
    }

    fn make_roadmap_doc(project: &str, slug: &str, title: &str) -> Document<Roadmap> {
        Document {
            frontmatter: make_roadmap(project, slug, title),
            body: String::new(),
        }
    }

    #[test]
    fn roadmap_summary_with_phases() {
        let doc = make_roadmap_doc("fbm", "two-way", "Two-Way Players");
        let phases = vec![
            (
                "phase-1-core".to_string(),
                make_phase_doc(1, "Core", PhaseStatus::Done),
            ),
            (
                "phase-2-service".to_string(),
                make_phase_doc(2, "Service", PhaseStatus::InProgress),
            ),
        ];
        let output = format_roadmap_summary(&doc, &phases);
        assert!(output.contains("# Two-Way Players"));
        assert!(output.contains("1/2 phases done"));
        assert!(output.contains("| 1 | Core | done |"));
        assert!(output.contains("| 2 | Service | in-progress |"));
    }

    #[test]
    fn roadmap_summary_no_phases() {
        let doc = make_roadmap_doc("fbm", "two-way", "Two-Way Players");
        let output = format_roadmap_summary(&doc, &[]);
        assert!(output.contains("No phases yet."));
    }

    #[test]
    fn roadmap_summary_with_body() {
        let mut doc = make_roadmap_doc("fbm", "two-way", "Two-Way Players");
        doc.body = "## Overview\n\nThis roadmap covers two-way player valuation.\n".to_string();
        let phases = vec![(
            "phase-1-core".to_string(),
            make_phase_doc(1, "Core", PhaseStatus::InProgress),
        )];
        let output = format_roadmap_summary(&doc, &phases);
        assert!(output.contains("| 1 | Core | in-progress |"));
        assert!(output.contains("## Overview"));
        assert!(output.contains("This roadmap covers two-way player valuation."));
    }

    #[test]
    fn roadmap_summary_no_phases_with_body() {
        let mut doc = make_roadmap_doc("fbm", "two-way", "Two-Way Players");
        doc.body = "Some body text.\n".to_string();
        let output = format_roadmap_summary(&doc, &[]);
        assert!(output.contains("No phases yet."));
        assert!(output.contains("Some body text."));
    }

    #[test]
    fn roadmap_summary_empty_body() {
        let doc = make_roadmap_doc("fbm", "two-way", "Two-Way Players");
        let output = format_roadmap_summary(&doc, &[]);
        // Should end with "No phases yet.\n" — no trailing blank line from body
        assert!(output.ends_with("No phases yet.\n"));
    }

    #[test]
    fn phase_detail_with_completed() {
        let doc = make_phase_doc(1, "Core", PhaseStatus::Done);
        let output = format_phase_detail("phase-1-core", &doc);
        assert!(output.contains("# Phase 1: Core"));
        assert!(output.contains("Status: done"));
        assert!(output.contains("Completed: 2026-03-14"));
        assert!(output.contains("Stem: phase-1-core"));
    }

    #[test]
    fn phase_detail_without_completed() {
        let doc = make_phase_doc(2, "Service", PhaseStatus::NotStarted);
        let output = format_phase_detail("phase-2-service", &doc);
        assert!(output.contains("Status: not-started"));
        assert!(!output.contains("Completed:"));
    }

    #[test]
    fn phase_list_with_entries() {
        let phases = vec![
            (
                "phase-1-core".to_string(),
                make_phase_doc(1, "Core", PhaseStatus::Done),
            ),
            (
                "phase-2-service".to_string(),
                make_phase_doc(2, "Service", PhaseStatus::InProgress),
            ),
        ];
        let output = format_phase_list(&phases);
        assert!(output.contains("| # | Phase | Status | Stem |"));
        assert!(output.contains("| 1 | Core | done | phase-1-core |"));
        assert!(output.contains("| 2 | Service | in-progress | phase-2-service |"));
    }

    #[test]
    fn phase_list_empty() {
        let output = format_phase_list(&[]);
        assert_eq!(output, "No phases yet.\n");
    }

    #[test]
    fn roadmap_list_with_entries() {
        let entries = vec![
            (
                Document {
                    frontmatter: make_roadmap("fbm", "alpha", "Alpha"),
                    body: String::new(),
                },
                vec![
                    ("p1".to_string(), make_phase_doc(1, "P1", PhaseStatus::Done)),
                    (
                        "p2".to_string(),
                        make_phase_doc(2, "P2", PhaseStatus::InProgress),
                    ),
                ],
            ),
            (
                Document {
                    frontmatter: make_roadmap("fbm", "beta", "Beta"),
                    body: String::new(),
                },
                Vec::new(),
            ),
        ];
        let output = format_roadmap_list(&entries);
        assert!(output.contains("alpha — Alpha (1/2 done)"));
        assert!(output.contains("beta — Beta (no phases)"));
    }

    #[test]
    fn roadmap_list_empty() {
        let output = format_roadmap_list(&[]);
        assert!(output.contains("No roadmaps found."));
    }

    fn make_task_doc(
        title: &str,
        status: TaskStatus,
        priority: Priority,
        tags: Option<Vec<String>>,
    ) -> Document<Task> {
        Document {
            frontmatter: Task {
                project: "fbm".to_string(),
                title: title.to_string(),
                status,
                priority,
                created: NaiveDate::from_ymd_opt(2026, 3, 15).unwrap(),
                tags,
            },
            body: String::new(),
        }
    }

    #[test]
    fn task_detail_basic() {
        let doc = make_task_doc("Fix the bug", TaskStatus::Open, Priority::High, None);
        let output = format_task_detail("fix-bug", &doc);
        assert!(output.contains("# Fix the bug"));
        assert!(output.contains("Slug: fix-bug"));
        assert!(output.contains("Status: open"));
        assert!(output.contains("Priority: high"));
        assert!(output.contains("Created: 2026-03-15"));
        assert!(!output.contains("Tags:"));
    }

    #[test]
    fn task_detail_with_tags() {
        let doc = make_task_doc(
            "Fix",
            TaskStatus::Open,
            Priority::Low,
            Some(vec!["bug".to_string(), "urgent".to_string()]),
        );
        let output = format_task_detail("fix", &doc);
        assert!(output.contains("Tags: bug, urgent"));
    }

    #[test]
    fn task_detail_with_body() {
        let mut doc = make_task_doc("Fix", TaskStatus::Open, Priority::Low, None);
        doc.body = "Some details.\n".to_string();
        let output = format_task_detail("fix", &doc);
        assert!(output.contains("Some details."));
    }

    #[test]
    fn task_list_with_entries() {
        let tasks = vec![
            (
                "fix-bug".to_string(),
                make_task_doc("Fix Bug", TaskStatus::Open, Priority::High, None),
            ),
            (
                "add-feature".to_string(),
                make_task_doc(
                    "Add Feature",
                    TaskStatus::InProgress,
                    Priority::Medium,
                    None,
                ),
            ),
        ];
        let output = format_task_list(&tasks);
        assert!(output.contains("| Slug | Title | Status | Priority |"));
        assert!(output.contains("| fix-bug | Fix Bug | open | high |"));
        assert!(output.contains("| add-feature | Add Feature | in-progress | medium |"));
    }

    #[test]
    fn task_list_empty() {
        let output = format_task_list(&[]);
        assert_eq!(output, "No tasks found.\n");
    }

    // -- format_index tests --

    fn make_index_entry(
        slug: &str,
        project: &str,
        phase_count: usize,
        done_count: usize,
        deps: Option<Vec<String>>,
    ) -> RoadmapIndexEntry {
        RoadmapIndexEntry {
            slug: slug.to_string(),
            project: project.to_string(),
            phase_count,
            done_count,
            dependencies: deps,
        }
    }

    #[test]
    fn index_single_project_no_deps() {
        let projects = vec![ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![make_index_entry("alpha", "fbm", 3, 1, None)],
            tasks: vec![(
                "fix-bug".to_string(),
                make_task_doc("Fix Bug", TaskStatus::Open, Priority::High, None),
            )],
        }];
        let output = format_index(&projects);
        assert!(output.contains("# Plan Index"));
        assert!(output.contains("## Project: fbm"));
        assert!(
            output
                .contains("| [alpha](projects/fbm/roadmaps/alpha/roadmap.md) | 3 | 1/3 done | — |")
        );
        assert!(output.contains("| fix-bug | high | open |"));
        assert!(!output.contains("Dependency Graph"));
    }

    #[test]
    fn index_multiple_projects_sorted() {
        let projects = vec![
            ProjectIndex {
                name: "aaa".to_string(),
                roadmaps: vec![],
                tasks: vec![],
            },
            ProjectIndex {
                name: "zzz".to_string(),
                roadmaps: vec![],
                tasks: vec![],
            },
        ];
        let output = format_index(&projects);
        let aaa_pos = output.find("## Project: aaa").unwrap();
        let zzz_pos = output.find("## Project: zzz").unwrap();
        assert!(aaa_pos < zzz_pos);
    }

    #[test]
    fn index_tasks_priority_order() {
        let projects = vec![ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![],
            tasks: vec![
                (
                    "aaa-task".to_string(),
                    make_task_doc("AAA", TaskStatus::Open, Priority::Critical, None),
                ),
                (
                    "bbb-task".to_string(),
                    make_task_doc("BBB", TaskStatus::Open, Priority::High, None),
                ),
                (
                    "ccc-task".to_string(),
                    make_task_doc("CCC", TaskStatus::Open, Priority::Low, None),
                ),
            ],
        }];
        let output = format_index(&projects);
        let crit_pos = output.find("aaa-task").unwrap();
        let high_pos = output.find("bbb-task").unwrap();
        let low_pos = output.find("ccc-task").unwrap();
        assert!(crit_pos < high_pos);
        assert!(high_pos < low_pos);
    }

    #[test]
    fn index_dependency_graph_present() {
        let projects = vec![ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![
                make_index_entry("alpha", "fbm", 2, 2, None),
                make_index_entry("beta", "fbm", 3, 0, Some(vec!["alpha".to_string()])),
            ],
            tasks: vec![],
        }];
        let output = format_index(&projects);
        assert!(output.contains("### Dependency Graph"));
        assert!(output.contains("- **beta** → alpha"));
    }

    #[test]
    fn index_dependency_graph_absent() {
        let projects = vec![ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![make_index_entry("alpha", "fbm", 2, 1, None)],
            tasks: vec![],
        }];
        let output = format_index(&projects);
        assert!(!output.contains("Dependency Graph"));
    }

    #[test]
    fn index_progress_labels() {
        let not_started = make_index_entry("a", "p", 3, 0, None);
        let complete = make_index_entry("b", "p", 3, 3, None);
        let no_phases = make_index_entry("c", "p", 0, 0, None);
        let projects = vec![ProjectIndex {
            name: "p".to_string(),
            roadmaps: vec![not_started, complete, no_phases],
            tasks: vec![],
        }];
        let output = format_index(&projects);
        assert!(output.contains("not started"));
        assert!(output.contains("complete"));
        assert!(output.contains("no phases"));
    }

    #[test]
    fn index_idempotent() {
        let projects = vec![ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![make_index_entry("alpha", "fbm", 2, 1, None)],
            tasks: vec![(
                "fix".to_string(),
                make_task_doc("Fix", TaskStatus::Open, Priority::Low, None),
            )],
        }];
        let first = format_index(&projects);
        let second = format_index(&projects);
        assert_eq!(first, second);
    }

    #[test]
    fn index_empty() {
        let output = format_index(&[]);
        assert!(output.contains("# Plan Index"));
    }

    #[test]
    fn index_no_roadmaps_no_tasks() {
        let projects = vec![ProjectIndex {
            name: "empty".to_string(),
            roadmaps: vec![],
            tasks: vec![],
        }];
        let output = format_index(&projects);
        assert!(output.contains("No roadmaps."));
        assert!(output.contains("No tasks."));
    }

    // -- Markdown format tests --

    #[test]
    fn roadmap_summary_md_with_phases() {
        let doc = make_roadmap_doc("fbm", "two-way", "Two-Way Players");
        let phases = vec![
            (
                "phase-1-core".to_string(),
                make_phase_doc(1, "Core", PhaseStatus::Done),
            ),
            (
                "phase-2-service".to_string(),
                make_phase_doc(2, "Service", PhaseStatus::InProgress),
            ),
        ];
        let output = format_roadmap_summary_md(&doc, &phases);
        assert!(output.contains("# Two-Way Players"));
        assert!(output.contains("- **Project:** fbm"));
        assert!(output.contains("- **Slug:** two-way"));
        assert!(output.contains("- **Progress:** 1/2 phases done"));
        assert!(output.contains("|---:"));
        assert!(output.contains("| 1 | Core | done |"));
        assert!(output.contains("| 2 | Service | in-progress |"));
    }

    #[test]
    fn roadmap_summary_md_no_phases() {
        let doc = make_roadmap_doc("fbm", "two-way", "Two-Way Players");
        let output = format_roadmap_summary_md(&doc, &[]);
        assert!(output.contains("No phases yet."));
        assert!(!output.contains("- **Progress:**"));
    }

    #[test]
    fn roadmap_summary_md_with_body() {
        let mut doc = make_roadmap_doc("fbm", "two-way", "Two-Way Players");
        doc.body = "## Overview\n\nDetails here.\n".to_string();
        let phases = vec![(
            "phase-1-core".to_string(),
            make_phase_doc(1, "Core", PhaseStatus::InProgress),
        )];
        let output = format_roadmap_summary_md(&doc, &phases);
        assert!(output.contains("## Overview"));
        assert!(output.contains("Details here."));
    }

    #[test]
    fn roadmap_list_md_with_entries() {
        let entries = vec![
            (
                Document {
                    frontmatter: make_roadmap("fbm", "alpha", "Alpha"),
                    body: String::new(),
                },
                vec![
                    ("p1".to_string(), make_phase_doc(1, "P1", PhaseStatus::Done)),
                    (
                        "p2".to_string(),
                        make_phase_doc(2, "P2", PhaseStatus::InProgress),
                    ),
                ],
            ),
            (
                Document {
                    frontmatter: make_roadmap("fbm", "beta", "Beta"),
                    body: String::new(),
                },
                Vec::new(),
            ),
        ];
        let output = format_roadmap_list_md(&entries);
        assert!(output.contains("## Roadmaps"));
        assert!(output.contains("| Slug |"));
        assert!(output.contains("|---"));
        assert!(output.contains("| alpha | Alpha | 1/2 done |"));
        assert!(output.contains("| beta | Beta | no phases |"));
    }

    #[test]
    fn roadmap_list_md_empty() {
        let output = format_roadmap_list_md(&[]);
        assert_eq!(output, "No roadmaps found.\n");
    }

    #[test]
    fn phase_detail_md_with_completed() {
        let doc = make_phase_doc(1, "Core", PhaseStatus::Done);
        let output = format_phase_detail_md("phase-1-core", &doc);
        assert!(output.contains("# Phase 1: Core"));
        assert!(output.contains("- **Stem:** phase-1-core"));
        assert!(output.contains("- **Status:** done"));
        assert!(output.contains("- **Completed:** 2026-03-14"));
    }

    #[test]
    fn phase_detail_md_without_completed() {
        let doc = make_phase_doc(2, "Service", PhaseStatus::NotStarted);
        let output = format_phase_detail_md("phase-2-service", &doc);
        assert!(output.contains("- **Status:** not-started"));
        assert!(!output.contains("- **Completed:**"));
    }

    #[test]
    fn phase_detail_md_with_body() {
        let mut doc = make_phase_doc(1, "Core", PhaseStatus::InProgress);
        doc.body = "Implementation details.\n".to_string();
        let output = format_phase_detail_md("phase-1-core", &doc);
        assert!(output.contains("Implementation details."));
    }

    #[test]
    fn phase_list_md_with_entries() {
        let phases = vec![
            (
                "phase-1-core".to_string(),
                make_phase_doc(1, "Core", PhaseStatus::Done),
            ),
            (
                "phase-2-service".to_string(),
                make_phase_doc(2, "Service", PhaseStatus::InProgress),
            ),
        ];
        let output = format_phase_list_md(&phases);
        assert!(output.contains("## Phases"));
        assert!(output.contains("|---:"));
        assert!(output.contains("| 1 | Core | done | phase-1-core |"));
        assert!(output.contains("| 2 | Service | in-progress | phase-2-service |"));
    }

    #[test]
    fn phase_list_md_empty() {
        let output = format_phase_list_md(&[]);
        assert_eq!(output, "No phases yet.\n");
    }

    #[test]
    fn task_detail_md_basic() {
        let doc = make_task_doc("Fix the bug", TaskStatus::Open, Priority::High, None);
        let output = format_task_detail_md("fix-bug", &doc);
        assert!(output.contains("# Fix the bug"));
        assert!(output.contains("- **Slug:** fix-bug"));
        assert!(output.contains("- **Status:** open"));
        assert!(output.contains("- **Priority:** high"));
        assert!(output.contains("- **Created:** 2026-03-15"));
        assert!(!output.contains("- **Tags:**"));
    }

    #[test]
    fn task_detail_md_with_tags() {
        let doc = make_task_doc(
            "Fix",
            TaskStatus::Open,
            Priority::Low,
            Some(vec!["bug".to_string(), "urgent".to_string()]),
        );
        let output = format_task_detail_md("fix", &doc);
        assert!(output.contains("- **Tags:** bug, urgent"));
    }

    #[test]
    fn task_detail_md_with_body() {
        let mut doc = make_task_doc("Fix", TaskStatus::Open, Priority::Low, None);
        doc.body = "Some details.\n".to_string();
        let output = format_task_detail_md("fix", &doc);
        assert!(output.contains("Some details."));
    }

    #[test]
    fn task_list_md_with_entries() {
        let tasks = vec![
            (
                "fix-bug".to_string(),
                make_task_doc("Fix Bug", TaskStatus::Open, Priority::High, None),
            ),
            (
                "add-feature".to_string(),
                make_task_doc(
                    "Add Feature",
                    TaskStatus::InProgress,
                    Priority::Medium,
                    None,
                ),
            ),
        ];
        let output = format_task_list_md(&tasks);
        assert!(output.contains("## Tasks"));
        assert!(output.contains("| Slug | Title | Status | Priority |"));
        assert!(output.contains("|---"));
        assert!(output.contains("| fix-bug | Fix Bug | open | high |"));
        assert!(output.contains("| add-feature | Add Feature | in-progress | medium |"));
    }

    #[test]
    fn task_list_md_empty() {
        let output = format_task_list_md(&[]);
        assert_eq!(output, "No tasks found.\n");
    }

    #[test]
    fn search_results_md_with_results() {
        let results = vec![SearchResult {
            kind: crate::search::ItemKind::Task,
            identifier: "fix-bug".to_string(),
            project: "acme".to_string(),
            title: "Fix Bug".to_string(),
            snippet: "Fix the login bug".to_string(),
            score: 100,
        }];
        let output = format_search_results_md(&results);
        assert!(output.contains("## Search Results"));
        assert!(output.contains("|---:"));
        assert!(output.contains("| 1 |"));
        assert!(output.contains("Fix Bug"));
        assert!(output.contains("fix-bug"));
    }

    #[test]
    fn search_results_md_empty() {
        let output = format_search_results_md(&[]);
        assert_eq!(output, "No results found.\n");
    }
}
