/// Display formatting functions for roadmaps, phases, and projects.
///
/// Pure functions — no I/O. These produce human-readable output strings.
use crate::document::Document;
use crate::model::{Phase, PhaseStatus, Roadmap, Task};

/// Aggregated index data for a single project.
pub struct ProjectIndex {
    /// Project name.
    pub name: String,
    /// Roadmap index entries, pre-sorted by slug.
    pub roadmaps: Vec<RoadmapIndexEntry>,
    /// Tasks as `(slug, Document<Task>)`, pre-sorted by priority desc then slug asc.
    pub tasks: Vec<(String, Document<Task>)>,
}

/// Summary data for a roadmap in the index.
pub struct RoadmapIndexEntry {
    /// Roadmap slug.
    pub slug: String,
    /// Project this roadmap belongs to.
    pub project: String,
    /// Total number of phases.
    pub phase_count: usize,
    /// Number of completed phases.
    pub done_count: usize,
    /// Optional list of dependency roadmap slugs.
    pub dependencies: Option<Vec<String>>,
}

/// Formats the plan index as a Markdown string.
///
/// Produces the complete `INDEX.md` content from pre-aggregated project data.
#[must_use]
pub fn format_index(projects: &[ProjectIndex]) -> String {
    let mut out = String::new();
    out.push_str("# Plan Index\n\n");
    out.push_str("<!-- This file is auto-generated by rdm. Do not edit by hand. -->\n");

    for project in projects {
        out.push_str(&format!("\n## Project: {}\n\n", project.name));

        // Roadmaps table
        if project.roadmaps.is_empty() {
            out.push_str("No roadmaps.\n");
        } else {
            out.push_str("| Roadmap | Phases | Progress | Dependencies |\n");
            out.push_str("|---------|--------|----------|--------------|\n");
            for rm in &project.roadmaps {
                let progress = if rm.phase_count == 0 {
                    "no phases".to_string()
                } else if rm.done_count == 0 {
                    "not started".to_string()
                } else if rm.done_count == rm.phase_count {
                    "complete".to_string()
                } else {
                    format!("{}/{} done", rm.done_count, rm.phase_count)
                };
                let deps = rm
                    .dependencies
                    .as_ref()
                    .map(|d| d.join(", "))
                    .unwrap_or_else(|| "—".to_string());
                let link = format!(
                    "[{}](projects/{}/roadmaps/{}/roadmap.md)",
                    rm.slug, rm.project, rm.slug
                );
                out.push_str(&format!(
                    "| {} | {} | {} | {} |\n",
                    link, rm.phase_count, progress, deps
                ));
            }

            // Dependency graph (only if any roadmap has deps)
            let has_deps = project
                .roadmaps
                .iter()
                .any(|rm| rm.dependencies.as_ref().is_some_and(|d| !d.is_empty()));
            if has_deps {
                out.push_str("\n### Dependency Graph\n\n");
                for rm in &project.roadmaps {
                    if let Some(ref deps) = rm.dependencies {
                        if !deps.is_empty() {
                            out.push_str(&format!("- **{}** → {}\n", rm.slug, deps.join(", ")));
                        }
                    }
                }
            }
        }

        // Tasks table
        out.push('\n');
        if project.tasks.is_empty() {
            out.push_str("No tasks.\n");
        } else {
            out.push_str("| Task | Priority | Status |\n");
            out.push_str("|------|----------|--------|\n");
            for (slug, doc) in &project.tasks {
                let fm = &doc.frontmatter;
                out.push_str(&format!("| {} | {} | {} |\n", slug, fm.priority, fm.status));
            }
        }
    }

    out
}

/// A roadmap document paired with its phases (stem + phase document).
pub type RoadmapWithPhases = (Document<Roadmap>, Vec<(String, Document<Phase>)>);

/// Formats a roadmap summary with a status table of its phases and optional body.
///
/// Displays the roadmap title, project/slug metadata, phase progress table,
/// and any body content from the document. If the document body is non-empty,
/// it is appended after the phase table (or "No phases yet." message).
pub fn format_roadmap_summary(
    doc: &Document<Roadmap>,
    phases: &[(String, Document<Phase>)],
) -> String {
    let roadmap = &doc.frontmatter;
    let mut out = String::new();
    out.push_str(&format!("# {}\n\n", roadmap.title));
    out.push_str(&format!(
        "Project: {}  Slug: {}\n",
        roadmap.project, roadmap.roadmap
    ));

    if phases.is_empty() {
        out.push_str("\nNo phases yet.\n");
    } else {
        let done_count = phases
            .iter()
            .filter(|(_, d)| d.frontmatter.status == PhaseStatus::Done)
            .count();
        out.push_str(&format!(
            "Progress: {}/{} phases done\n\n",
            done_count,
            phases.len()
        ));

        out.push_str("| # | Phase | Status |\n");
        out.push_str("|---|-------|--------|\n");
        for (_, d) in phases {
            let fm = &d.frontmatter;
            out.push_str(&format!(
                "| {} | {} | {} |\n",
                fm.phase, fm.title, fm.status
            ));
        }
    }

    if !doc.body.is_empty() {
        out.push_str(&format!("\n{}", doc.body));
    }
    out
}

/// Formats a single phase detail view.
pub fn format_phase_detail(stem: &str, doc: &Document<Phase>) -> String {
    let fm = &doc.frontmatter;
    let mut out = String::new();
    out.push_str(&format!("# Phase {}: {}\n\n", fm.phase, fm.title));
    out.push_str(&format!("Stem: {stem}\n"));
    out.push_str(&format!("Status: {}\n", fm.status));
    if let Some(date) = fm.completed {
        out.push_str(&format!("Completed: {date}\n"));
    }
    if !doc.body.is_empty() {
        out.push_str(&format!("\n{}", doc.body));
    }
    out
}

/// Formats a list of phases as a table with number, title, status, and stem.
pub fn format_phase_list(phases: &[(String, Document<Phase>)]) -> String {
    if phases.is_empty() {
        return "No phases yet.\n".to_string();
    }

    let mut out = String::new();
    out.push_str("| # | Phase | Status | Stem |\n");
    out.push_str("|---|-------|--------|------|\n");
    for (stem, doc) in phases {
        let fm = &doc.frontmatter;
        out.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            fm.phase, fm.title, fm.status, stem
        ));
    }
    out
}

/// Formats a list of roadmaps with progress summaries.
pub fn format_roadmap_list(entries: &[RoadmapWithPhases]) -> String {
    if entries.is_empty() {
        return "No roadmaps found.\n".to_string();
    }

    let mut out = String::new();
    for (roadmap_doc, phases) in entries {
        let rm = &roadmap_doc.frontmatter;
        let done = phases
            .iter()
            .filter(|(_, doc)| doc.frontmatter.status == PhaseStatus::Done)
            .count();
        let total = phases.len();
        if total > 0 {
            out.push_str(&format!(
                "{} — {} ({}/{} done)\n",
                rm.roadmap, rm.title, done, total
            ));
        } else {
            out.push_str(&format!("{} — {} (no phases)\n", rm.roadmap, rm.title));
        }
    }
    out
}

/// Formats a single task detail view.
pub fn format_task_detail(slug: &str, doc: &Document<Task>) -> String {
    let fm = &doc.frontmatter;
    let mut out = String::new();
    out.push_str(&format!("# {}\n\n", fm.title));
    out.push_str(&format!("Slug: {slug}\n"));
    out.push_str(&format!("Status: {}\n", fm.status));
    out.push_str(&format!("Priority: {}\n", fm.priority));
    out.push_str(&format!("Created: {}\n", fm.created));
    if let Some(tags) = &fm.tags {
        out.push_str(&format!("Tags: {}\n", tags.join(", ")));
    }
    if !doc.body.is_empty() {
        out.push_str(&format!("\n{}", doc.body));
    }
    out
}

/// Formats a list of tasks as a table with slug, title, status, and priority columns.
pub fn format_task_list(tasks: &[(String, Document<Task>)]) -> String {
    if tasks.is_empty() {
        return "No tasks found.\n".to_string();
    }

    let mut out = String::new();
    out.push_str("| Slug | Title | Status | Priority |\n");
    out.push_str("|------|-------|--------|----------|\n");
    for (slug, doc) in tasks {
        let fm = &doc.frontmatter;
        out.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            slug, fm.title, fm.status, fm.priority
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{PhaseStatus, Priority, TaskStatus};
    use chrono::NaiveDate;

    fn make_phase_doc(num: u32, title: &str, status: PhaseStatus) -> Document<Phase> {
        Document {
            frontmatter: Phase {
                phase: num,
                title: title.to_string(),
                status,
                completed: if status == PhaseStatus::Done {
                    Some(NaiveDate::from_ymd_opt(2026, 3, 14).unwrap())
                } else {
                    None
                },
            },
            body: String::new(),
        }
    }

    fn make_roadmap(project: &str, slug: &str, title: &str) -> Roadmap {
        Roadmap {
            project: project.to_string(),
            roadmap: slug.to_string(),
            title: title.to_string(),
            phases: Vec::new(),
            dependencies: None,
        }
    }

    fn make_roadmap_doc(project: &str, slug: &str, title: &str) -> Document<Roadmap> {
        Document {
            frontmatter: make_roadmap(project, slug, title),
            body: String::new(),
        }
    }

    #[test]
    fn roadmap_summary_with_phases() {
        let doc = make_roadmap_doc("fbm", "two-way", "Two-Way Players");
        let phases = vec![
            (
                "phase-1-core".to_string(),
                make_phase_doc(1, "Core", PhaseStatus::Done),
            ),
            (
                "phase-2-service".to_string(),
                make_phase_doc(2, "Service", PhaseStatus::InProgress),
            ),
        ];
        let output = format_roadmap_summary(&doc, &phases);
        assert!(output.contains("# Two-Way Players"));
        assert!(output.contains("1/2 phases done"));
        assert!(output.contains("| 1 | Core | done |"));
        assert!(output.contains("| 2 | Service | in-progress |"));
    }

    #[test]
    fn roadmap_summary_no_phases() {
        let doc = make_roadmap_doc("fbm", "two-way", "Two-Way Players");
        let output = format_roadmap_summary(&doc, &[]);
        assert!(output.contains("No phases yet."));
    }

    #[test]
    fn roadmap_summary_with_body() {
        let mut doc = make_roadmap_doc("fbm", "two-way", "Two-Way Players");
        doc.body = "## Overview\n\nThis roadmap covers two-way player valuation.\n".to_string();
        let phases = vec![(
            "phase-1-core".to_string(),
            make_phase_doc(1, "Core", PhaseStatus::InProgress),
        )];
        let output = format_roadmap_summary(&doc, &phases);
        assert!(output.contains("| 1 | Core | in-progress |"));
        assert!(output.contains("## Overview"));
        assert!(output.contains("This roadmap covers two-way player valuation."));
    }

    #[test]
    fn roadmap_summary_no_phases_with_body() {
        let mut doc = make_roadmap_doc("fbm", "two-way", "Two-Way Players");
        doc.body = "Some body text.\n".to_string();
        let output = format_roadmap_summary(&doc, &[]);
        assert!(output.contains("No phases yet."));
        assert!(output.contains("Some body text."));
    }

    #[test]
    fn roadmap_summary_empty_body() {
        let doc = make_roadmap_doc("fbm", "two-way", "Two-Way Players");
        let output = format_roadmap_summary(&doc, &[]);
        // Should end with "No phases yet.\n" — no trailing blank line from body
        assert!(output.ends_with("No phases yet.\n"));
    }

    #[test]
    fn phase_detail_with_completed() {
        let doc = make_phase_doc(1, "Core", PhaseStatus::Done);
        let output = format_phase_detail("phase-1-core", &doc);
        assert!(output.contains("# Phase 1: Core"));
        assert!(output.contains("Status: done"));
        assert!(output.contains("Completed: 2026-03-14"));
        assert!(output.contains("Stem: phase-1-core"));
    }

    #[test]
    fn phase_detail_without_completed() {
        let doc = make_phase_doc(2, "Service", PhaseStatus::NotStarted);
        let output = format_phase_detail("phase-2-service", &doc);
        assert!(output.contains("Status: not-started"));
        assert!(!output.contains("Completed:"));
    }

    #[test]
    fn phase_list_with_entries() {
        let phases = vec![
            (
                "phase-1-core".to_string(),
                make_phase_doc(1, "Core", PhaseStatus::Done),
            ),
            (
                "phase-2-service".to_string(),
                make_phase_doc(2, "Service", PhaseStatus::InProgress),
            ),
        ];
        let output = format_phase_list(&phases);
        assert!(output.contains("| # | Phase | Status | Stem |"));
        assert!(output.contains("| 1 | Core | done | phase-1-core |"));
        assert!(output.contains("| 2 | Service | in-progress | phase-2-service |"));
    }

    #[test]
    fn phase_list_empty() {
        let output = format_phase_list(&[]);
        assert_eq!(output, "No phases yet.\n");
    }

    #[test]
    fn roadmap_list_with_entries() {
        let entries = vec![
            (
                Document {
                    frontmatter: make_roadmap("fbm", "alpha", "Alpha"),
                    body: String::new(),
                },
                vec![
                    ("p1".to_string(), make_phase_doc(1, "P1", PhaseStatus::Done)),
                    (
                        "p2".to_string(),
                        make_phase_doc(2, "P2", PhaseStatus::InProgress),
                    ),
                ],
            ),
            (
                Document {
                    frontmatter: make_roadmap("fbm", "beta", "Beta"),
                    body: String::new(),
                },
                Vec::new(),
            ),
        ];
        let output = format_roadmap_list(&entries);
        assert!(output.contains("alpha — Alpha (1/2 done)"));
        assert!(output.contains("beta — Beta (no phases)"));
    }

    #[test]
    fn roadmap_list_empty() {
        let output = format_roadmap_list(&[]);
        assert!(output.contains("No roadmaps found."));
    }

    fn make_task_doc(
        title: &str,
        status: TaskStatus,
        priority: Priority,
        tags: Option<Vec<String>>,
    ) -> Document<Task> {
        Document {
            frontmatter: Task {
                project: "fbm".to_string(),
                title: title.to_string(),
                status,
                priority,
                created: NaiveDate::from_ymd_opt(2026, 3, 15).unwrap(),
                tags,
            },
            body: String::new(),
        }
    }

    #[test]
    fn task_detail_basic() {
        let doc = make_task_doc("Fix the bug", TaskStatus::Open, Priority::High, None);
        let output = format_task_detail("fix-bug", &doc);
        assert!(output.contains("# Fix the bug"));
        assert!(output.contains("Slug: fix-bug"));
        assert!(output.contains("Status: open"));
        assert!(output.contains("Priority: high"));
        assert!(output.contains("Created: 2026-03-15"));
        assert!(!output.contains("Tags:"));
    }

    #[test]
    fn task_detail_with_tags() {
        let doc = make_task_doc(
            "Fix",
            TaskStatus::Open,
            Priority::Low,
            Some(vec!["bug".to_string(), "urgent".to_string()]),
        );
        let output = format_task_detail("fix", &doc);
        assert!(output.contains("Tags: bug, urgent"));
    }

    #[test]
    fn task_detail_with_body() {
        let mut doc = make_task_doc("Fix", TaskStatus::Open, Priority::Low, None);
        doc.body = "Some details.\n".to_string();
        let output = format_task_detail("fix", &doc);
        assert!(output.contains("Some details."));
    }

    #[test]
    fn task_list_with_entries() {
        let tasks = vec![
            (
                "fix-bug".to_string(),
                make_task_doc("Fix Bug", TaskStatus::Open, Priority::High, None),
            ),
            (
                "add-feature".to_string(),
                make_task_doc(
                    "Add Feature",
                    TaskStatus::InProgress,
                    Priority::Medium,
                    None,
                ),
            ),
        ];
        let output = format_task_list(&tasks);
        assert!(output.contains("| Slug | Title | Status | Priority |"));
        assert!(output.contains("| fix-bug | Fix Bug | open | high |"));
        assert!(output.contains("| add-feature | Add Feature | in-progress | medium |"));
    }

    #[test]
    fn task_list_empty() {
        let output = format_task_list(&[]);
        assert_eq!(output, "No tasks found.\n");
    }

    // -- format_index tests --

    fn make_index_entry(
        slug: &str,
        project: &str,
        phase_count: usize,
        done_count: usize,
        deps: Option<Vec<String>>,
    ) -> RoadmapIndexEntry {
        RoadmapIndexEntry {
            slug: slug.to_string(),
            project: project.to_string(),
            phase_count,
            done_count,
            dependencies: deps,
        }
    }

    #[test]
    fn index_single_project_no_deps() {
        let projects = vec![ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![make_index_entry("alpha", "fbm", 3, 1, None)],
            tasks: vec![(
                "fix-bug".to_string(),
                make_task_doc("Fix Bug", TaskStatus::Open, Priority::High, None),
            )],
        }];
        let output = format_index(&projects);
        assert!(output.contains("# Plan Index"));
        assert!(output.contains("## Project: fbm"));
        assert!(
            output
                .contains("| [alpha](projects/fbm/roadmaps/alpha/roadmap.md) | 3 | 1/3 done | — |")
        );
        assert!(output.contains("| fix-bug | high | open |"));
        assert!(!output.contains("Dependency Graph"));
    }

    #[test]
    fn index_multiple_projects_sorted() {
        let projects = vec![
            ProjectIndex {
                name: "aaa".to_string(),
                roadmaps: vec![],
                tasks: vec![],
            },
            ProjectIndex {
                name: "zzz".to_string(),
                roadmaps: vec![],
                tasks: vec![],
            },
        ];
        let output = format_index(&projects);
        let aaa_pos = output.find("## Project: aaa").unwrap();
        let zzz_pos = output.find("## Project: zzz").unwrap();
        assert!(aaa_pos < zzz_pos);
    }

    #[test]
    fn index_tasks_priority_order() {
        let projects = vec![ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![],
            tasks: vec![
                (
                    "aaa-task".to_string(),
                    make_task_doc("AAA", TaskStatus::Open, Priority::Critical, None),
                ),
                (
                    "bbb-task".to_string(),
                    make_task_doc("BBB", TaskStatus::Open, Priority::High, None),
                ),
                (
                    "ccc-task".to_string(),
                    make_task_doc("CCC", TaskStatus::Open, Priority::Low, None),
                ),
            ],
        }];
        let output = format_index(&projects);
        let crit_pos = output.find("aaa-task").unwrap();
        let high_pos = output.find("bbb-task").unwrap();
        let low_pos = output.find("ccc-task").unwrap();
        assert!(crit_pos < high_pos);
        assert!(high_pos < low_pos);
    }

    #[test]
    fn index_dependency_graph_present() {
        let projects = vec![ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![
                make_index_entry("alpha", "fbm", 2, 2, None),
                make_index_entry("beta", "fbm", 3, 0, Some(vec!["alpha".to_string()])),
            ],
            tasks: vec![],
        }];
        let output = format_index(&projects);
        assert!(output.contains("### Dependency Graph"));
        assert!(output.contains("- **beta** → alpha"));
    }

    #[test]
    fn index_dependency_graph_absent() {
        let projects = vec![ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![make_index_entry("alpha", "fbm", 2, 1, None)],
            tasks: vec![],
        }];
        let output = format_index(&projects);
        assert!(!output.contains("Dependency Graph"));
    }

    #[test]
    fn index_progress_labels() {
        let not_started = make_index_entry("a", "p", 3, 0, None);
        let complete = make_index_entry("b", "p", 3, 3, None);
        let no_phases = make_index_entry("c", "p", 0, 0, None);
        let projects = vec![ProjectIndex {
            name: "p".to_string(),
            roadmaps: vec![not_started, complete, no_phases],
            tasks: vec![],
        }];
        let output = format_index(&projects);
        assert!(output.contains("not started"));
        assert!(output.contains("complete"));
        assert!(output.contains("no phases"));
    }

    #[test]
    fn index_idempotent() {
        let projects = vec![ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![make_index_entry("alpha", "fbm", 2, 1, None)],
            tasks: vec![(
                "fix".to_string(),
                make_task_doc("Fix", TaskStatus::Open, Priority::Low, None),
            )],
        }];
        let first = format_index(&projects);
        let second = format_index(&projects);
        assert_eq!(first, second);
    }

    #[test]
    fn index_empty() {
        let output = format_index(&[]);
        assert!(output.contains("# Plan Index"));
    }

    #[test]
    fn index_no_roadmaps_no_tasks() {
        let projects = vec![ProjectIndex {
            name: "empty".to_string(),
            roadmaps: vec![],
            tasks: vec![],
        }];
        let output = format_index(&projects);
        assert!(output.contains("No roadmaps."));
        assert!(output.contains("No tasks."));
    }
}
