[tools]
rust = "1.94"
"cargo:cargo-deny" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-watch" = "latest"
"cargo:cargo-dist" = "latest"

[env]
RUSTFLAGS = "-D warnings"
RDM_ROOT = "{{env.HOME}}/Projects/rdm-atlas-repo"
RDM_PROJECT = "rdm"
