//! Plan repo initialization.

use crate::config::Config;
use crate::error::{Error, Result};
use crate::store::Store;

/// Initializes a new plan repo with the default config.
///
/// Creates `rdm.toml` (with default values) and `INDEX.md`.
/// Equivalent to `init_with_config(store, Config::default())`.
///
/// # Errors
///
/// Returns [`Error::AlreadyInitialized`] if `rdm.toml` already exists, or
/// [`Error::Io`] if file creation fails.
pub fn init(store: &mut impl Store) -> Result<()> {
    init_with_config(store, Config::default())
}

/// Initializes a new plan repo with the given config.
///
/// Creates `rdm.toml` (populated from `config`) and `INDEX.md`.
/// The config is validated before any files are written.
///
/// # Errors
///
/// Returns [`Error::AlreadyInitialized`] if `rdm.toml` already exists,
/// [`Error::InvalidConfigValue`] if the config fails validation, or
/// [`Error::Io`] if file creation fails.
pub fn init_with_config(store: &mut impl Store, config: Config) -> Result<()> {
    config.validate()?;

    if store.exists(&crate::paths::config_path()) {
        return Err(Error::AlreadyInitialized);
    }

    let toml_str = config.to_toml()?;
    let config_path = crate::paths::config_path();
    store.write(&config_path, toml_str)?;

    let index_path = crate::paths::index_path();
    store.write(
        &index_path,
        "# Plan Index\n\n<!-- This file is auto-generated by rdm. Do not edit by hand. -->\n"
            .to_string(),
    )?;

    store.commit()?;
    Ok(())
}
