use crate::config::Config;
use crate::error::{Error, Result};
use crate::store::Store;

use super::PlanRepo;

impl<S: Store> PlanRepo<S> {
    // -- Init --

    /// Initializes a new plan repo with the given store and default config.
    ///
    /// Creates `rdm.toml` (with default values) and `INDEX.md`.
    /// Equivalent to `init_with_config(store, Config::default())`.
    ///
    /// # Errors
    ///
    /// Returns [`Error::AlreadyInitialized`] if `rdm.toml` already exists, or
    /// [`Error::Io`] if file creation fails.
    pub fn init(store: S) -> Result<Self> {
        Self::init_with_config(store, Config::default())
    }

    /// Initializes a new plan repo with the given store and config.
    ///
    /// Creates `rdm.toml` (populated from `config`) and `INDEX.md`.
    /// The config is validated before any files are written.
    ///
    /// # Errors
    ///
    /// Returns [`Error::AlreadyInitialized`] if `rdm.toml` already exists,
    /// [`Error::InvalidConfigValue`] if the config fails validation, or
    /// [`Error::Io`] if file creation fails.
    pub fn init_with_config(store: S, config: Config) -> Result<Self> {
        config.validate()?;

        let mut repo = PlanRepo { store };

        if repo.store.exists(&repo.config_path()) {
            return Err(Error::AlreadyInitialized);
        }

        let toml_str = config.to_toml()?;
        let config_path = repo.config_path();
        repo.store.write(&config_path, toml_str)?;

        let index_path = repo.index_path();
        repo.store.write(
            &index_path,
            "# Plan Index\n\n<!-- This file is auto-generated by rdm. Do not edit by hand. -->\n"
                .to_string(),
        )?;

        repo.store.commit()?;
        Ok(repo)
    }
}
