/// INDEX.md generation functions.
///
/// Pure functions that produce Markdown content for INDEX.md files
/// from pre-aggregated project data.
use crate::ast;
use crate::document::Document;
use crate::model::Task;

/// Aggregated index data for a single project.
pub struct ProjectIndex {
    /// Project name.
    pub name: String,
    /// Roadmap index entries, pre-sorted by slug.
    pub roadmaps: Vec<RoadmapIndexEntry>,
    /// Tasks as `(slug, Document<Task>)`, pre-sorted by priority desc then slug asc.
    pub tasks: Vec<(String, Document<Task>)>,
}

/// Summary data for a roadmap in the index.
pub struct RoadmapIndexEntry {
    /// Roadmap slug.
    pub slug: String,
    /// Project this roadmap belongs to.
    pub project: String,
    /// Total number of phases.
    pub phase_count: usize,
    /// Number of completed phases.
    pub done_count: usize,
    /// Optional list of dependency roadmap slugs.
    pub dependencies: Option<Vec<String>>,
}

/// Formats the top-level `INDEX.md` as a lightweight summary table.
///
/// Each project gets a single row linking to its per-project `INDEX.md`.
/// Progress is computed across all roadmaps: total done phases / total phases.
#[must_use]
pub fn format_top_level_index(projects: &[ProjectIndex]) -> String {
    let mut d = ast::Document::new();
    d.heading(1, "Plan Index");
    d.push(ast::Block::BlankLine);
    d.push(ast::Block::HtmlComment(
        "This file is auto-generated by rdm. Do not edit by hand.".to_owned(),
    ));

    if !projects.is_empty() {
        d.push(ast::Block::BlankLine);
        let headers = vec!["Project", "Roadmaps", "Tasks", "Progress"]
            .into_iter()
            .map(|h| vec![ast::Inline::text(h)])
            .collect();
        let rows = projects
            .iter()
            .map(|p| {
                let roadmap_count = p.roadmaps.len();
                let task_count = p.tasks.len();
                let total_phases: usize = p.roadmaps.iter().map(|rm| rm.phase_count).sum();
                let done_phases: usize = p.roadmaps.iter().map(|rm| rm.done_count).sum();
                let progress = if roadmap_count == 0 {
                    "no roadmaps".to_string()
                } else if done_phases == 0 {
                    "not started".to_string()
                } else if done_phases == total_phases {
                    "complete".to_string()
                } else {
                    format!("{}/{} done", done_phases, total_phases)
                };
                let link_url = format!("projects/{}/INDEX.md", p.name);
                vec![
                    vec![ast::Inline::link(&p.name, &link_url)],
                    vec![ast::Inline::Text(roadmap_count.to_string())],
                    vec![ast::Inline::Text(task_count.to_string())],
                    vec![ast::Inline::Text(progress)],
                ]
            })
            .collect();
        d.push(ast::Block::Table { headers, rows });
    }

    d.to_string()
}

/// Formats the plan index as a Markdown string.
///
/// Produces the complete `INDEX.md` content from pre-aggregated project data.
#[must_use]
pub fn format_index(projects: &[ProjectIndex]) -> String {
    let mut d = ast::Document::new();
    d.heading(1, "Plan Index");
    d.push(ast::Block::BlankLine);
    d.push(ast::Block::HtmlComment(
        "This file is auto-generated by rdm. Do not edit by hand.".to_owned(),
    ));

    for project in projects {
        d.push(ast::Block::BlankLine);
        d.heading(2, &format!("Project: {}", project.name));
        d.push(ast::Block::BlankLine);

        // Roadmaps table
        if project.roadmaps.is_empty() {
            d.paragraph("No roadmaps.");
        } else {
            let headers = vec!["Roadmap", "Phases", "Progress", "Dependencies"]
                .into_iter()
                .map(|h| vec![ast::Inline::text(h)])
                .collect();
            let rows = project
                .roadmaps
                .iter()
                .map(|rm| {
                    let progress = if rm.phase_count == 0 {
                        "no phases".to_string()
                    } else if rm.done_count == 0 {
                        "not started".to_string()
                    } else if rm.done_count == rm.phase_count {
                        "complete".to_string()
                    } else {
                        format!("{}/{} done", rm.done_count, rm.phase_count)
                    };
                    let deps = rm
                        .dependencies
                        .as_ref()
                        .map(|dep| dep.join(", "))
                        .unwrap_or_else(|| "\u{2014}".to_string());
                    let link_url =
                        format!("projects/{}/roadmaps/{}/roadmap.md", rm.project, rm.slug);
                    vec![
                        vec![ast::Inline::link(&rm.slug, &link_url)],
                        vec![ast::Inline::Text(rm.phase_count.to_string())],
                        vec![ast::Inline::Text(progress)],
                        vec![ast::Inline::Text(deps)],
                    ]
                })
                .collect();
            d.push(ast::Block::Table { headers, rows });

            // Dependency graph (only if any roadmap has deps)
            let has_deps = project
                .roadmaps
                .iter()
                .any(|rm| rm.dependencies.as_ref().is_some_and(|dep| !dep.is_empty()));
            if has_deps {
                d.push(ast::Block::BlankLine);
                d.heading(3, "Dependency Graph");
                d.push(ast::Block::BlankLine);
                let items = project
                    .roadmaps
                    .iter()
                    .filter(|rm| rm.dependencies.as_ref().is_some_and(|dep| !dep.is_empty()))
                    .map(|rm| {
                        let deps = rm.dependencies.as_ref().unwrap();
                        vec![
                            ast::Inline::bold(&rm.slug),
                            ast::Inline::Text(format!(" \u{2192} {}", deps.join(", "))),
                        ]
                    })
                    .collect();
                d.push(ast::Block::UnorderedList { items });
            }
        }

        // Tasks table
        d.push(ast::Block::BlankLine);
        if project.tasks.is_empty() {
            d.paragraph("No tasks.");
        } else {
            let headers = vec!["Task", "Priority", "Status"]
                .into_iter()
                .map(|h| vec![ast::Inline::text(h)])
                .collect();
            let rows = project
                .tasks
                .iter()
                .map(|(slug, doc)| {
                    let fm = &doc.frontmatter;
                    vec![
                        vec![ast::Inline::Text(slug.clone())],
                        vec![ast::Inline::Text(fm.priority.to_string())],
                        vec![ast::Inline::Text(fm.status.to_string())],
                    ]
                })
                .collect();
            d.push(ast::Block::Table { headers, rows });
        }
    }

    d.to_string()
}

/// Formats a per-project index as a standalone Markdown document.
///
/// Produces `projects/{name}/INDEX.md` content with relative links
/// (e.g. `roadmaps/{slug}/roadmap.md` instead of `projects/{name}/roadmaps/...`).
#[must_use]
pub fn format_project_index(project: &ProjectIndex) -> String {
    let mut d = ast::Document::new();
    d.heading(1, &format!("Project: {}", project.name));
    d.push(ast::Block::BlankLine);
    d.push(ast::Block::HtmlComment(
        "This file is auto-generated by rdm. Do not edit by hand.".to_owned(),
    ));
    d.push(ast::Block::BlankLine);

    // Roadmaps table
    if project.roadmaps.is_empty() {
        d.paragraph("No roadmaps.");
    } else {
        let headers = vec!["Roadmap", "Phases", "Progress", "Dependencies"]
            .into_iter()
            .map(|h| vec![ast::Inline::text(h)])
            .collect();
        let rows = project
            .roadmaps
            .iter()
            .map(|rm| {
                let progress = if rm.phase_count == 0 {
                    "no phases".to_string()
                } else if rm.done_count == 0 {
                    "not started".to_string()
                } else if rm.done_count == rm.phase_count {
                    "complete".to_string()
                } else {
                    format!("{}/{} done", rm.done_count, rm.phase_count)
                };
                let deps = rm
                    .dependencies
                    .as_ref()
                    .map(|dep| dep.join(", "))
                    .unwrap_or_else(|| "\u{2014}".to_string());
                // Relative link — no projects/{name}/ prefix
                let link_url = format!("roadmaps/{}/roadmap.md", rm.slug);
                vec![
                    vec![ast::Inline::link(&rm.slug, &link_url)],
                    vec![ast::Inline::Text(rm.phase_count.to_string())],
                    vec![ast::Inline::Text(progress)],
                    vec![ast::Inline::Text(deps)],
                ]
            })
            .collect();
        d.push(ast::Block::Table { headers, rows });

        // Dependency graph (only if any roadmap has deps)
        let has_deps = project
            .roadmaps
            .iter()
            .any(|rm| rm.dependencies.as_ref().is_some_and(|dep| !dep.is_empty()));
        if has_deps {
            d.push(ast::Block::BlankLine);
            d.heading(3, "Dependency Graph");
            d.push(ast::Block::BlankLine);
            let items = project
                .roadmaps
                .iter()
                .filter(|rm| rm.dependencies.as_ref().is_some_and(|dep| !dep.is_empty()))
                .map(|rm| {
                    let deps = rm.dependencies.as_ref().unwrap();
                    vec![
                        ast::Inline::bold(&rm.slug),
                        ast::Inline::Text(format!(" \u{2192} {}", deps.join(", "))),
                    ]
                })
                .collect();
            d.push(ast::Block::UnorderedList { items });
        }
    }

    // Tasks table
    d.push(ast::Block::BlankLine);
    if project.tasks.is_empty() {
        d.paragraph("No tasks.");
    } else {
        let headers = vec!["Task", "Priority", "Status"]
            .into_iter()
            .map(|h| vec![ast::Inline::text(h)])
            .collect();
        let rows = project
            .tasks
            .iter()
            .map(|(slug, doc)| {
                let fm = &doc.frontmatter;
                vec![
                    vec![ast::Inline::Text(slug.clone())],
                    vec![ast::Inline::Text(fm.priority.to_string())],
                    vec![ast::Inline::Text(fm.status.to_string())],
                ]
            })
            .collect();
        d.push(ast::Block::Table { headers, rows });
    }

    d.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Priority, TaskStatus};
    use chrono::NaiveDate;

    fn make_task_doc(
        title: &str,
        status: TaskStatus,
        priority: Priority,
        _tags: Option<Vec<String>>,
    ) -> Document<Task> {
        Document {
            frontmatter: Task {
                project: "fbm".to_string(),
                title: title.to_string(),
                status,
                priority,
                created: NaiveDate::from_ymd_opt(2026, 3, 15).unwrap(),
                tags: _tags,
                completed: None,
                commit: None,
            },
            body: String::new(),
        }
    }

    fn make_index_entry(
        slug: &str,
        project: &str,
        phase_count: usize,
        done_count: usize,
        deps: Option<Vec<String>>,
    ) -> RoadmapIndexEntry {
        RoadmapIndexEntry {
            slug: slug.to_string(),
            project: project.to_string(),
            phase_count,
            done_count,
            dependencies: deps,
        }
    }

    // -- format_project_index tests --

    #[test]
    fn project_index_heading_and_comment() {
        let pi = ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![],
            tasks: vec![],
        };
        let output = format_project_index(&pi);
        assert!(output.contains("# Project: fbm"));
        assert!(output.contains("auto-generated by rdm"));
    }

    #[test]
    fn project_index_relative_roadmap_links() {
        let pi = ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![make_index_entry("alpha", "fbm", 3, 1, None)],
            tasks: vec![],
        };
        let output = format_project_index(&pi);
        // Links should be relative — no "projects/fbm/" prefix
        assert!(output.contains("roadmaps/alpha/roadmap.md"));
        assert!(!output.contains("projects/fbm/"));
    }

    #[test]
    fn project_index_no_roadmaps_no_tasks() {
        let pi = ProjectIndex {
            name: "empty".to_string(),
            roadmaps: vec![],
            tasks: vec![],
        };
        let output = format_project_index(&pi);
        assert!(output.contains("No roadmaps."));
        assert!(output.contains("No tasks."));
    }

    #[test]
    fn project_index_dependency_graph() {
        let pi = ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![
                make_index_entry("alpha", "fbm", 2, 2, None),
                make_index_entry("beta", "fbm", 3, 0, Some(vec!["alpha".to_string()])),
            ],
            tasks: vec![],
        };
        let output = format_project_index(&pi);
        assert!(output.contains("### Dependency Graph"));
        assert!(output.contains("**beta**"));
    }

    #[test]
    fn project_index_no_dependency_graph_when_none() {
        let pi = ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![make_index_entry("alpha", "fbm", 2, 1, None)],
            tasks: vec![],
        };
        let output = format_project_index(&pi);
        assert!(!output.contains("Dependency Graph"));
    }

    #[test]
    fn project_index_progress_labels() {
        let pi = ProjectIndex {
            name: "p".to_string(),
            roadmaps: vec![
                make_index_entry("a", "p", 3, 0, None),
                make_index_entry("b", "p", 3, 3, None),
                make_index_entry("c", "p", 0, 0, None),
            ],
            tasks: vec![],
        };
        let output = format_project_index(&pi);
        assert!(output.contains("not started"));
        assert!(output.contains("complete"));
        assert!(output.contains("no phases"));
    }

    #[test]
    fn project_index_idempotent() {
        let pi = ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![make_index_entry("alpha", "fbm", 2, 1, None)],
            tasks: vec![(
                "fix".to_string(),
                make_task_doc("Fix", TaskStatus::Open, Priority::Low, None),
            )],
        };
        let first = format_project_index(&pi);
        let second = format_project_index(&pi);
        assert_eq!(first, second);
    }

    // -- format_top_level_index tests --

    #[test]
    fn top_level_index_heading_and_comment() {
        let output = format_top_level_index(&[]);
        assert!(output.contains("# Plan Index"));
        assert!(output.contains("auto-generated by rdm"));
        assert!(!output.contains("| Project"));
    }

    #[test]
    fn top_level_index_project_link() {
        let projects = vec![ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![make_index_entry("alpha", "fbm", 3, 1, None)],
            tasks: vec![(
                "fix-bug".to_string(),
                make_task_doc("Fix Bug", TaskStatus::Open, Priority::High, None),
            )],
        }];
        let output = format_top_level_index(&projects);
        assert!(output.contains("[fbm](projects/fbm/INDEX.md)"));
        assert!(output.contains("| 1 |")); // roadmap count
        assert!(output.contains("1/3 done"));
    }

    #[test]
    fn top_level_index_summary_counts() {
        let projects = vec![ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![
                make_index_entry("alpha", "fbm", 3, 1, None),
                make_index_entry("beta", "fbm", 2, 2, None),
            ],
            tasks: vec![
                (
                    "t1".to_string(),
                    make_task_doc("T1", TaskStatus::Open, Priority::Low, None),
                ),
                (
                    "t2".to_string(),
                    make_task_doc("T2", TaskStatus::Open, Priority::High, None),
                ),
                (
                    "t3".to_string(),
                    make_task_doc("T3", TaskStatus::Done, Priority::Low, None),
                ),
            ],
        }];
        let output = format_top_level_index(&projects);
        // 2 roadmaps, 3 tasks, 3/5 done (1+2 done out of 3+2 total phases)
        assert!(output.contains("| 2 |"));
        assert!(output.contains("| 3 |"));
        assert!(output.contains("3/5 done"));
    }

    #[test]
    fn top_level_index_progress_not_started() {
        let projects = vec![ProjectIndex {
            name: "p".to_string(),
            roadmaps: vec![make_index_entry("a", "p", 3, 0, None)],
            tasks: vec![],
        }];
        let output = format_top_level_index(&projects);
        assert!(output.contains("not started"));
    }

    #[test]
    fn top_level_index_progress_complete() {
        let projects = vec![ProjectIndex {
            name: "p".to_string(),
            roadmaps: vec![make_index_entry("a", "p", 3, 3, None)],
            tasks: vec![],
        }];
        let output = format_top_level_index(&projects);
        assert!(output.contains("complete"));
    }

    #[test]
    fn top_level_index_progress_no_roadmaps() {
        let projects = vec![ProjectIndex {
            name: "p".to_string(),
            roadmaps: vec![],
            tasks: vec![],
        }];
        let output = format_top_level_index(&projects);
        assert!(output.contains("no roadmaps"));
    }

    #[test]
    fn top_level_index_progress_no_phases() {
        let projects = vec![ProjectIndex {
            name: "p".to_string(),
            roadmaps: vec![make_index_entry("a", "p", 0, 0, None)],
            tasks: vec![],
        }];
        let output = format_top_level_index(&projects);
        assert!(output.contains("not started"));
    }

    #[test]
    fn top_level_index_multiple_projects() {
        let projects = vec![
            ProjectIndex {
                name: "aaa".to_string(),
                roadmaps: vec![],
                tasks: vec![],
            },
            ProjectIndex {
                name: "zzz".to_string(),
                roadmaps: vec![],
                tasks: vec![],
            },
        ];
        let output = format_top_level_index(&projects);
        let aaa_pos = output.find("[aaa]").unwrap();
        let zzz_pos = output.find("[zzz]").unwrap();
        assert!(aaa_pos < zzz_pos);
    }

    #[test]
    fn top_level_index_idempotent() {
        let projects = vec![ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![make_index_entry("alpha", "fbm", 2, 1, None)],
            tasks: vec![(
                "fix".to_string(),
                make_task_doc("Fix", TaskStatus::Open, Priority::Low, None),
            )],
        }];
        let first = format_top_level_index(&projects);
        let second = format_top_level_index(&projects);
        assert_eq!(first, second);
    }

    // -- format_index tests --

    #[test]
    fn index_single_project_no_deps() {
        let projects = vec![ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![make_index_entry("alpha", "fbm", 3, 1, None)],
            tasks: vec![(
                "fix-bug".to_string(),
                make_task_doc("Fix Bug", TaskStatus::Open, Priority::High, None),
            )],
        }];
        let output = format_index(&projects);
        assert!(output.contains("# Plan Index"));
        assert!(output.contains("## Project: fbm"));
        assert!(
            output
                .contains("| [alpha](projects/fbm/roadmaps/alpha/roadmap.md) | 3 | 1/3 done | — |")
        );
        assert!(output.contains("| fix-bug | high | open |"));
        assert!(!output.contains("Dependency Graph"));
    }

    #[test]
    fn index_multiple_projects_sorted() {
        let projects = vec![
            ProjectIndex {
                name: "aaa".to_string(),
                roadmaps: vec![],
                tasks: vec![],
            },
            ProjectIndex {
                name: "zzz".to_string(),
                roadmaps: vec![],
                tasks: vec![],
            },
        ];
        let output = format_index(&projects);
        let aaa_pos = output.find("## Project: aaa").unwrap();
        let zzz_pos = output.find("## Project: zzz").unwrap();
        assert!(aaa_pos < zzz_pos);
    }

    #[test]
    fn index_tasks_priority_order() {
        let projects = vec![ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![],
            tasks: vec![
                (
                    "aaa-task".to_string(),
                    make_task_doc("AAA", TaskStatus::Open, Priority::Critical, None),
                ),
                (
                    "bbb-task".to_string(),
                    make_task_doc("BBB", TaskStatus::Open, Priority::High, None),
                ),
                (
                    "ccc-task".to_string(),
                    make_task_doc("CCC", TaskStatus::Open, Priority::Low, None),
                ),
            ],
        }];
        let output = format_index(&projects);
        let crit_pos = output.find("aaa-task").unwrap();
        let high_pos = output.find("bbb-task").unwrap();
        let low_pos = output.find("ccc-task").unwrap();
        assert!(crit_pos < high_pos);
        assert!(high_pos < low_pos);
    }

    #[test]
    fn index_dependency_graph_present() {
        let projects = vec![ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![
                make_index_entry("alpha", "fbm", 2, 2, None),
                make_index_entry("beta", "fbm", 3, 0, Some(vec!["alpha".to_string()])),
            ],
            tasks: vec![],
        }];
        let output = format_index(&projects);
        assert!(output.contains("### Dependency Graph"));
        assert!(output.contains("- **beta** → alpha"));
    }

    #[test]
    fn index_dependency_graph_absent() {
        let projects = vec![ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![make_index_entry("alpha", "fbm", 2, 1, None)],
            tasks: vec![],
        }];
        let output = format_index(&projects);
        assert!(!output.contains("Dependency Graph"));
    }

    #[test]
    fn index_progress_labels() {
        let not_started = make_index_entry("a", "p", 3, 0, None);
        let complete = make_index_entry("b", "p", 3, 3, None);
        let no_phases = make_index_entry("c", "p", 0, 0, None);
        let projects = vec![ProjectIndex {
            name: "p".to_string(),
            roadmaps: vec![not_started, complete, no_phases],
            tasks: vec![],
        }];
        let output = format_index(&projects);
        assert!(output.contains("not started"));
        assert!(output.contains("complete"));
        assert!(output.contains("no phases"));
    }

    #[test]
    fn index_idempotent() {
        let projects = vec![ProjectIndex {
            name: "fbm".to_string(),
            roadmaps: vec![make_index_entry("alpha", "fbm", 2, 1, None)],
            tasks: vec![(
                "fix".to_string(),
                make_task_doc("Fix", TaskStatus::Open, Priority::Low, None),
            )],
        }];
        let first = format_index(&projects);
        let second = format_index(&projects);
        assert_eq!(first, second);
    }

    #[test]
    fn index_empty() {
        let output = format_index(&[]);
        assert!(output.contains("# Plan Index"));
    }

    #[test]
    fn index_no_roadmaps_no_tasks() {
        let projects = vec![ProjectIndex {
            name: "empty".to_string(),
            roadmaps: vec![],
            tasks: vec![],
        }];
        let output = format_index(&projects);
        assert!(output.contains("No roadmaps."));
        assert!(output.contains("No tasks."));
    }
}
